<a href="https://colab.research.google.com/github/anirbansen3027/Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#attributes
print("a-ndim",a.ndim)
print("a-shape", a.shape)
print("a-size", a.size)
print("a-dtype", a.dtype)
print("a-itemsize", a.itemsize)

a-ndim 2
a-shape (2, 3)
a-size 6
a-dtype int64
a-itemsize 8


In [ ]:
#creation
print("zeros:", np.zeros((2,3)))
print("ones:", np.ones((2,3)))
print("np.full((2,2),9):", np.full((2,3),9))
print("empty:", np.empty((2,3)))
print("random decimals", np.random.rand(2,2))
print("random numbers", np.random.randint(1,10, size = (2,2)))
print("arange:", np.arange(2,10,2))
print("arange float:", np.arange(2,3,0.2))
print("linspace float:", np.linspace(2,3,5))

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
np.full((2,2),9): [[9 9 9]
 [9 9 9]]
empty: [[4.4e-323 4.4e-323 4.4e-323]
 [4.4e-323 4.4e-323 4.4e-323]]
random decimals [[0.61878281 0.02316479]
 [0.82278766 0.84033912]]
random numbers [[8 1]
 [7 4]]
arange: [2 4 6 8]
arange float: [2.  2.2 2.4 2.6 2.8]
linspace float: [2.   2.25 2.5  2.75 3.  ]


In [ ]:
#basic operations
o = np.array([True,False])
m = np.array([np.nan,np.inf, -np.inf])
#Not a Number (NaN), positive infinity and negative infinity evaluate to True because these are not equal to zero.
print("All True:",np.all(o))
print("All True-2:",np.all(m))
print("Any:", np.any(o))
n = np.array([[0,2,3,4],[5,6,10,0]])
print("Argmin Argmax", np.argmin(n,axis = 1), np.argmax(n,axis = 1))
print("Indexes to be kept for sorted", np.argsort(n))
#Count number of occurrences of each integer in array of non-negative values
print("Bincount",np.bincount(n.ravel()))
p = np.array([0.1,0.9,1.1,1.9])
print("Ceil and floor",np.ceil(p), np.floor(p))
print("Clip",np.clip(p,0.5,1.5))
print("Element wise diff", np.diff(p))
print("Np where", np.where(p<1,p,-1))
#Sort a structured array
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
print("sort", np.sort(a, order = 'name'))

All True: False
All True-2: True
Any: True
Argmin Argmax [0 3] [3 2]
Indexes to be kept for sorted [[0 1 2 3]
 [3 0 1 2]]
Bincount [2 0 1 1 1 1 1 0 0 0 1]
Ceil and floor [1. 1. 2. 2.] [0. 0. 1. 1.]
Clip [0.5 0.9 1.1 1.5]
Element wise diff [0.8 0.2 0.8]
Np where [ 0.1  0.9 -1.  -1. ]
sort [(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [ ]:
#arithmetic operations
a = np.array([1,2,3])
b = np.array([4,5,2])
print("a+b",a+b)
print("a**2",a**2)
print("a*b",a*b)
print("a@b",a@b)
print("a.dot(b)",a.dot(b))
a+=b
print("a+=b",a)
c = np.array([[1,2,3],[4,5,6]])
print("Total Sum",c.sum()) # same for min, max, prod
print("Row wise Sum", c.sum(axis = 0))
print("Column wise Sum", c.sum(axis = 1))
print("Column wise cumsum\n", c.cumsum(axis = 1))
print("exponentiate",np.exp(b))
print("square root",np.sqrt(b))
s = np.array([1,2,3,np.nan,np.nan])
print("Numpy min function",np.min(s))
print("Numpy nanmin function", np.nanmin(s))
print("Range", np.ptp(c,axis = 0))
print("percentile", np.percentile(b,50))
print("Correlation", np.corrcoef(a,b))
print("Covariance", np.cov(a,b))
print("Intersection", np.intersect1d(a,b))
print("Union", np.union1d(a,b))
print("Setdiff", np.setdiff1d(a,b))
print("SetXor", np.setxor1d(a,b))

a+b [5 7 5]
a**2 [1 4 9]
a*b [ 4 10  6]
a@b 20
a.dot(b) 20
a+=b [5 7 5]
Total Sum 21
Row wise Sum [5 7 9]
Column wise Sum [ 6 15]
Column wise cumsum
 [[ 1  3  6]
 [ 4  9 15]]
exponentiate [ 54.59815003 148.4131591    7.3890561 ]
square root [2.         2.23606798 1.41421356]
Numpy min function nan
Numpy nanmin function 1.0
Range [3 3 3]
percentile 4.0
Correlation [[1.         0.75592895]
 [0.75592895 1.        ]]
Covariance [[1.33333333 1.33333333]
 [1.33333333 2.33333333]]
Intersection [5]
Union [2 4 5 7]
Setdiff [7]
SetXor [2 4 7]


In [ ]:
#shape manipulation
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
print("ravel", x.ravel())
print("reshape", x.reshape(3,2))   #reshape() does not change your data (returns a view), but resize() does (returns a copy)
print("resize", np.resize(x,(3,3))) #repeated if necessary to fill out the required number of elements.
print("transpose", x.T)

ravel [1 2 3 4 5 6]
reshape [[1 2]
 [3 4]
 [5 6]]
resize [[1 2 3]
 [4 5 6]
 [1 2 3]]
transpose [[1 4]
 [2 5]
 [3 6]]


In [ ]:
#stacking/splitting
print("hstack\n", np.hstack((x,y)))
print("vstack\n", np.vstack((x,y)))
print("vsplit\n", np.vsplit(x,2))
print("hsplit\n", np.hsplit(x,[1]))

hstack
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
vstack
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vsplit
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
hsplit
 [array([[1],
       [4]]), array([[2, 3],
       [5, 6]])]


In [ ]:
#copy/views
a = np.array([1,2,3])
b = a.view()
c = c.copy()
b.reshape(3,1)
print(a.shape)
b[0]=99
print(a)
c[1] = 100
print(a)

(3,)
[99  2  3]
[99  2  3]


In [ ]:
#linear algebra
print("Inverse of a matrix", np.linalg.inv(np.array([[1,2],[3,4]])))
print(np.eye(2))
print(np.linalg.eig(np.array([[1,2],[3,4]])))
a=np.array([9,10])
b = np.array([1,2])
print(np.cross(a,b))

Inverse of a matrix [[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
8


In [ ]:
z = np.array([0,1,1,0])
print("std, var", np.std(z), np.var(z))

std, var 0.5 0.25
